Numpy library

In [2]:
import numpy as np

In [2]:
a= np.array([1,2,3,4,5])

In [4]:
print(a)
a

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [7]:
a=np.array([1, 2, 3], dtype=float)
a

array([1., 2., 3.])

In [8]:
a=np.array([1, 2, 3], dtype=str)
a

array(['1', '2', '3'], dtype='<U1')

In [9]:
len(a)

3

In [4]:
b= np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
len(b)

2

In [7]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
len(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [9]:
b.ndim

2

In [10]:
c.ndim

2

In [13]:
d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d.ndim)
print(d)
print(d.shape)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


Accessing and changing specific element, rows and columns etc.

In [15]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.ndim

2

In [16]:
##Get a specific element from 2D array
a[0,3]

np.int64(4)

In [17]:
a[1,4]

np.int64(12)

In [20]:
##Get a specific row from 2D array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
##get a specific column from 2D array
a[0:,1]

array([2, 9])

In [26]:
a[0,3]

np.int64(4)

In [27]:
a[0,3] = 20

In [28]:
a[0,3]

np.int64(20)

Zeroes and ones method in Numpy

In [31]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.full((3,3), 7, dtype=int)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [34]:
np.random.rand(3,3)

array([[0.04923561, 0.98979665, 0.86409773],
       [0.59973418, 0.78689424, 0.08766505],
       [0.90695732, 0.53224182, 0.98440438]])

In [38]:
np.random.randint(-5, 0, size=(3,3))

array([[-2, -3, -4],
       [-2, -2, -3],
       [-5, -2, -2]], dtype=int32)

In [45]:
###Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

EXtract all the first 3 rows of the last 5 coloumn of a given matrix

In [59]:
a=np.array([[1,2,3,4,5,6],
        [7,8,9,10,11,12],
        [13,14,15,16,17,18]
        ,[19,20,21,22,23,24]])

In [58]:
a[:3, 1:]

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18]])

In [70]:
n=5

In [71]:
z=np.zeros((n,n), dtype=int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [73]:
##MAke Middle row and column 1's
z[n//2,:] = 1
z[:, n//2] = 1
z

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])