Numpy library

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4,5])

In [4]:
print(a)
a

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [7]:
a=np.array([1, 2, 3], dtype=float)
a

array([1., 2., 3.])

In [8]:
a=np.array([1, 2, 3], dtype=str)
a

array(['1', '2', '3'], dtype='<U1')

In [9]:
len(a)

3